export class CreateAgentDto {
    Id:number
    AgentId:string
    Name:string
    Email:string
    Password:string
    Phone:string
    JoinAt:string
    Status:string
    IsActive:string
    Company:string
    Companyadd:string
    Area:string
    CompanyImage:string
    LogoPermission:number
    Markup:string
    Bonus:number
    Credit:number
    LoginIp:string
    Browser:string
    Platform:string
}
