export class CreateAgentDto {
    id:number
    agentId:string
    name:string
    email:string
    password:string
    phone:string
    joinAt:string
    status:string
    isActive:string
    company:string
    companyadd:string
    area:string
    companyImage:string
    logoPermission:number
    markup:string
    bonus:number
    credit:number
    loginIp:string
    browser:string
    platform:string
}
