export class createAgentLedgerDto {
    Id:number
    AgentId:string
    AgentSubId:string
    StaffId:string
    Deposit:number
    Purchase:number
    Loan:number
    ReturnMoney:number
    Void:number
    Refund:number
    Reissue:number
    Others:number
    Servicefee:number
    LastAmount:number
    TransactionId:string
    Details:string
    Reference:string
    ActionBy:string
    CreatedAt:string
}
