export class createAgentLedgerDto {
    id:number
    agentId:string
    agentSubId:string
    staffId:string
    deposit:number
    purchase:number
    loan:number
    returnMoney:number
    void:number
    refund:number
    reissue:number
    others:number
    servicefee:number
    lastAmount:number
    transactionId:string
    details:string
    reference:string
    actionBy:string
    createdAt:string
}
