import { Column, Entity, PrimaryGeneratedColumn } from "typeorm"

@Entity()
export class Segmentreturnway {
    @Column()
    @PrimaryGeneratedColumn()
    Id:number
    @Column()
    System:string
    @Column()
    Segment:string
    @Column()
    Pnr:string
    @Column()
    GoTransit1:string
    @Column()
    BackTransit1:string
    @Column()
    BackTransit2:string
    @Column()
    GoMarketingCareer1:string
    @Column()
    GoMarketingCareer2:string
    @Column()
    GoMarketingCareer3:string
    @Column()
    GoMarketingCareerName1:string
    @Column()
    GoMarketingCareerName2:string
    @Column()
    GoMarketingCareerName3:string
    @Column()
    GoMarketingFlight1:string
    @Column()
    GoMarketingFlight2:string
    @Column()
    GoMarketingFlight3:string
    @Column()
    GoOperatingCareer1:string
    @Column()
    GoOperatingCareer2:string
    @Column()
    GoOperatingCareer3:string
    @Column()
    GoOperatingFlight1:string
    @Column()
    GoOperatingFlight2:string
    @Column()
    GoOperatingFlight3:string
    @Column()
    GoDeparture1:string
    @Column()
    GoDeparture2:string
    @Column()
    GoDeparture3:string
    @Column()
    GoArrival1:string
    @Column()
    GoArrival2:string
    @Column()
    GoArrival3:string
    @Column()
    GoDepartureAirport1:string
    @Column()
    GoDepartureAirport2:string
    @Column()
    GoDepartureAirport3:string
    @Column()
    GoArrivalAirport1:string
    @Column()
    GoArrivalAirport2:string
    @Column()
    GoArrivalAirport3:string
    @Column()
    GoDepartureLocation1:string
    @Column()
    GoDepartureLocation2:string
    @Column()
    GoDepartureLocation3:string
    @Column()
    GoArrivalLocation1:string
    @Column()
    GoArrivalLocation2:string
    @Column()
    GoArrivalLocation3:string
    @Column()
    GoDepartureTime1:string
    @Column()
    GoDepartureTime2:string
    @Column()
    GoDepartureTime3:string
    @Column()
    GoArrivalTime1:string
    @Column()
    GoArrivalTime2:string
    @Column()
    GoArrivalTime3:string
    @Column()
    GoFlightDuration1:string
    @Column()
    GoFlightDuration2:string
    @Column()
    GoFlightDuration3:string
    @Column()
    GoBookingCode1:string
    @Column()
    GoBookingCode2:string
    @Column()
    GoBookingCode3:string
    @Column()
    GoDepTerminal1:number
    @Column()
    GoDepTerminal2:number
    @Column()
    GoDepTerminal3:number
    @Column()
    GoArrTerminal1:number
    @Column()
    GoArrTerminal2:number
    @Column()
    GoArrTerminal3:number
    @Column()
    BackMarketingCareer1:string
    @Column()
    BackMarketingCareer2:string
    @Column()
    BackMarketingCareer3:string
    @Column()
    BackMarketingCareerName1:string
    @Column()
    BackMarketingCareerName2 :string
    @Column()
    BackMarketingCareerName3:string
    @Column()
    BackMarketingFlight1:string
    @Column()
    BackMarketingFlight2:string
    @Column()
    BackMarketingFlight3:string
    BackOperatingCareer1:string
    @Column()
    BackOperatingCareer2:string
    @Column()
    BackOperatingCareer3:string
    @Column()
    BackOperatingFlight1:string
    @Column()
    BackOperatingFlight2:string
    @Column()
    BackOperatingFlight3:string
    @Column()
    BackDeparture1:string
    @Column()
    BackDeparture2:string
    @Column()
    BackDeparture3:string
    @Column()
    BackArrival1:string
    @Column()
    BackArrival2:string
    @Column()
    BackArrival3:string
    @Column()
    BackDepartureAirport1:string
    @Column()
    BackDepartureAirport2:string
    @Column()
    BackDepartureAirport3:string
    @Column()
    BackArrivalAirport1:string
    @Column()
    BackArrivalAirport2:string
    @Column()
    BackArrivalAirport3:string
    @Column()
    BackDepartureLocation1:string
    @Column()
    BackDepartureLocation2:string
    @Column()
    BackDepartureLocation3:string
    @Column()
    BackArrivalLocation1:string
    @Column()
    BackArrivalLocation2:string
    @Column()
    BackArrivalLocation3:string
    @Column()
    BackDepartureTime1:string
    @Column()
    BackDepartureTime2:string
    @Column()
    BackDepartureTime3:string
    @Column()
    BackArrivalTime1:string
    @Column()
    BackArrivalTime2:string
    @Column()
    BackArrivalTime3:string
    @Column()
    BackFlightDuration1:string
    @Column()
    BackFlightDuration2:string
    @Column()
    BackFlightDuration3:string
    @Column()
    BackBookingCode1:string
    @Column()
    BackBookingCode2:string
    @Column()
    BackBookingCode3:string
    @Column()
    BackdepTerminal1:number
    @Column()
    BackdepTerminal2:number
    @Column()
    BackdepTerminal3:number
    @Column()
    BackArrTerminal1:number
    @Column()
    BackArrTerminal2:number
    @Column()
    BackArrTerminal3:number
    @Column()
    SearchId:string
    @Column()
    ResultId:string
    @Column()
    CreatedAt:string
    @Column()
    UId:string
}
