import { Column, Entity, PrimaryGeneratedColumn } from "typeorm"

@Entity()

export class Segmentoneway {


@Column()   
@PrimaryGeneratedColumn()
Id:number
@Column() 
System:String
@Column() 
Pnr:String
@Column() 
Segment:number
@Column() 
Departure1:string
@Column() 
Departure2:string
@Column() 
Departure3:string
@Column() 
Departure4:string
@Column() 
Arrival1:string
@Column() 
Arrival2:string
@Column() 
Arrival3:string
@Column() 
Arrival4:String
@Column() 
DepartureTime1:String
@Column() 
DepartureTime2:String
@Column() 
DepartureTime3:String
@Column() 
DepartureTime4:String
@Column() 
ArrivalTime1:String
@Column() 
ArrivalTime2:String
@Column() 
ArrivalTime3:String
@Column() 
ArrivalTime4:String
@Column() 
FlightDuration1:String
@Column() 
FlightDuration2:String
@Column() 
FlightDuration3:String
@Column() 
FlightDuration4:String
@Column() 
Transit1:string
@Column() 
Transit2:string
@Column() 
Transit3:string
@Column() 
MarketingCareer1:String
@Column() 
MarketingCareer2:String
@Column() 
MarketingCareer3:String
@Column() 
MarketingCareer4:String
@Column() 
MarketingCareerName1 :String
@Column() 
MarketingCareerName2:String
@Column() 
MarketingCareerName3:String
@Column() 
MarketingCareerName4:String
@Column() 
MarketingFlight1:String
@Column() 
MarketingFlight2:String
@Column() 
MarketingFlight3:String
@Column() 
MarketingFlight4:String
@Column() 
OperatingCareer1:String
@Column() 
OperatingCareer2:String
@Column() 
OperatingCareer3:String
@Column() 
OperatingCareer4:String
@Column() 
OperatingFlight1:String
@Column() 
OperatingFlight2:String
@Column() 
OperatingFlight3:String
@Column() 
OperatingFlight4:String
@Column() 
DepartureAirport1:String
@Column() 
DepartureAirport2:String
@Column() 
DepartureAirport3:String
@Column() 
DepartureAirport4:String
@Column() 
ArrivalAirport1:String
@Column() 
ArrivalAirport2:String
@Column() 
ArrivalAirport3:String
@Column() 
ArrivalAirport4:String
@Column() 
DepartureLocation1:String
@Column() 
DepartureLocation2:String
@Column() 
DepartureLocation3:String
@Column() 
DepartureLocation4:String
@Column() 
ArrivalLocation1:String
@Column() 
ArrivalLocation2:String
@Column() 
ArrivalLocation3:String
@Column() 
ArrivalLocation4:String
@Column() 
Bookingcode1:String
@Column() 
Bookingcode2:String
@Column() 
Bookingcode3:String
@Column() 
Bookingcode4:String
@Column() 
DepartureTerminal1:number
@Column() 
DepartureTerminal2:number
@Column() 
DepartureTerminal3:number
@Column() 
DepartureTerminal4:number
@Column() 
ArrivalTerminal1:number
@Column() 
ArrivalTerminal2:number
@Column() 
ArrivalTerminal3:number
@Column() 
ArrivalTerminal4:number
@Column() 
AdultBag:String
@Column() 
ChildBag:String
@Column() 
InfantBag:String
@Column() 
ResultId:String
@Column() 
SearchId:String
@Column() 
CreatedAt:String
@Column() 
UId:string
}
